[[redirects]]
  from = "/horario/*"
  to = "/index.html"
  status = 200

[[redirects]]
    from = "/tareas/*"
    to = "/index.html"
    status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
